export enum EnvironmentProprety {
  ACCESS_TOKEN_EXPIRATION_TIME = 'ACCESS_TOKEN_EXPIRATION_TIME',
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  DB_URL = 'DB_URL',
  DB_DATABASE = 'DB_DATABASE',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  I18N_FALLBACK_LANGUAGE = 'I18N_FALLBACK_LANGUAGE',
  REFRESH_TOKEN_EXPIRATION_TIME = 'REFRESH_TOKEN_EXPIRATION_TIME',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
}
